# Generated by Django 3.1.2 on 2020-10-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.SmallIntegerField(choices=[('-5', -5), ('-4', -4), ('-3', -3), ('-2', -2), ('-1', -1), ('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='-5'),
        ),
    ]
