# Generated by Django 3.1.2 on 2020-10-10 02:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20201009_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Member',
        ),
    ]
