# Generated by Django 3.1.2 on 2020-10-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201009_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
