# Generated by Django 3.1.2 on 2020-10-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_unit_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='amenities',
            field=models.CharField(choices=[('ac', 'Air Conditioning'), ('ch', 'Central Heating'), ('ra', 'Rustic Heating(Radiator)'), ('wd', 'In Unit Washer/Dryer'), ('lf', 'Laundry Facilities'), ('p', 'Parking'), ('fw', 'Free Wifi'), ('fc', 'Free Cable'), ('sp', 'Swimming Pool'), ('fc', 'Fitness Center'), ('cd', 'Cat/Dog Friendly'), ('ui', 'Utilities Included'), ('m', 'Free Pets(Mice Infestation)'), ('r', 'Free Pest Control(Roach Infestation)')], default='ac', max_length=2),
        ),
    ]
