# Generated by Django 3.1.2 on 2020-10-11 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201010_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.manager'),
        ),
    ]
