# Generated by Django 3.1.2 on 2020-10-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201010_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='amenities',
        ),
    ]
