# Generated by Django 3.1.2 on 2020-10-11 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_unit_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.amenities'),
            preserve_default=False,
        ),
    ]
