# Generated by Django 3.1.2 on 2020-10-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_unit_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='amenities',
        ),
        migrations.AddField(
            model_name='amenities',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.unit'),
            preserve_default=False,
        ),
    ]
