# Generated by Django 3.1.2 on 2020-10-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20201011_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.SmallIntegerField(choices=[('-5', -5), ('-4', -4), ('-3', -3), ('-2', -2), ('-1', -1), ('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='0')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('privatelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.privatelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.SmallIntegerField(choices=[('-5', -5), ('-4', -4), ('-3', -3), ('-2', -2), ('-1', -1), ('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='0')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='UnitComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.SmallIntegerField(choices=[('-5', -5), ('-4', -4), ('-3', -3), ('-2', -2), ('-1', -1), ('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='0')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
