# Generated by Django 3.1.2 on 2020-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20201011_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcomment',
            name='rating',
            field=models.SmallIntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default='0'),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='rating',
            field=models.SmallIntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default='0'),
        ),
        migrations.AlterField(
            model_name='unitcomment',
            name='rating',
            field=models.SmallIntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default='0'),
        ),
    ]
