# Generated by Django 3.1.2 on 2020-10-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20201011_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcomment',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='managercomment',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='unitcomment',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
