# Generated by Django 3.1.2 on 2020-10-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_managerphoto_profilephoto_unitphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
    ]
